version: '3.8'
services:

  panda-chatbot:
    build: ../../ChatBOT
    ports:
      - "6000:8000"
    networks:
      - panda_network
    container_name: pandachatbot
    expose:
      - 8000

  panda-db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=panda
      - MYSQL_ROOT_PASSWORD=nguyenkhanh2kpi
    ports:
      - 10051:3306
    expose:
      - 3306
    networks:
      - panda_network
    container_name: panda-mysql
    
  panda-backend:
    build:
      context: ../../Back_end
      dockerfile: Dockerfile
    container_name: panda-backend-container
    depends_on:
      - panda-db
    restart: unless-stopped
    ports:
      - 9090:8080
    environment:
      spring.datasource.url: jdbc:mysql://panda-db:3306/panda
      spring.datasource.username: root
      spring.datasource.password: nguyenkhanh2kpi
      server.servlet.context-path: /api
    networks:
      - panda_network
    expose:
      - 8080
    image: panda-backend


  panda-nginx:
    image: nginx:1.23.3
    build: 
      context: .
    container_name: panda-nginx
    ports:
      - 10046:80
    volumes:
      - ../../Front-end/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - panda-db
      - panda-backend
      - panda-chatbot
    networks:
      - panda_network


volumes:
  webdata-panda:

networks:
  panda_network:
    driver: bridge


